#!/usr/bin/env python3
"""Universal notification/content receiver.

This service intentionally does NOT parse or extract any business fields. It only accepts
POSTed content, annotates receive time, and appends one JSON object per line to a
file so any downstream program can consume the records later.

Authentication is mandatory. On startup the service reads NOTIFY_RELAY_KEY from
key.env; if the file/key is missing, it creates a new random key and writes it to
key.env with 0600 permissions.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import secrets
import threading
import time
import urllib.parse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

_WRITE_LOCK = threading.Lock()
_ARGS: argparse.Namespace
_RELAY_KEY = ""
_LATEST: dict[str, Any] | None = None
_COUNT = 0


def utc_now() -> tuple[float, str]:
    ts = time.time()
    iso = _dt.datetime.fromtimestamp(ts, tz=_dt.timezone.utc).isoformat().replace("+00:00", "Z")
    return ts, iso


def json_response(handler: BaseHTTPRequestHandler, status: int, obj: dict[str, Any]) -> None:
    raw = json.dumps(obj, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json; charset=utf-8")
    handler.send_header("Content-Length", str(len(raw)))
    handler.end_headers()
    handler.wfile.write(raw)


def parse_key_env(text: str) -> str:
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        if k.strip() == "NOTIFY_RELAY_KEY":
            val = v.strip().strip('"').strip("'")
            if val:
                return val
    return ""


def write_key_env(path: Path, key: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    ts = _dt.datetime.now(tz=_dt.timezone.utc).isoformat().replace("+00:00", "Z")
    content = (
        "# Auto-generated by notify_receiver.py\n"
        f"# generated_at={ts}\n"
        "# Put this value into the Android App 接收密钥 field. Do not share it.\n"
        f"NOTIFY_RELAY_KEY={key}\n"
    )
    fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(content)
        f.flush()
        os.fsync(f.fileno())
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def load_or_create_key(path: Path) -> str:
    if path.exists():
        key = parse_key_env(path.read_text(encoding="utf-8", errors="replace"))
        if key:
            try:
                os.chmod(path, 0o600)
            except OSError:
                pass
            return key
    key = secrets.token_urlsafe(32)
    write_key_env(path, key)
    return key


def read_body(handler: BaseHTTPRequestHandler) -> bytes:
    try:
        length = int(handler.headers.get("Content-Length", "0") or "0")
    except ValueError:
        length = 0
    if length > _ARGS.max_body_bytes:
        raise ValueError(f"body too large: {length} > {_ARGS.max_body_bytes}")
    return handler.rfile.read(length) if length > 0 else b""


def parse_payload(raw: bytes, content_type: str) -> Any:
    if not raw:
        return {}
    text = raw.decode("utf-8", errors="replace")
    ctype = (content_type or "").split(";", 1)[0].strip().lower()
    if ctype == "application/json" or text.lstrip().startswith(("{", "[")):
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            return {"raw_text": text, "parse_error": "invalid_json"}
    if ctype == "application/x-www-form-urlencoded":
        parsed = urllib.parse.parse_qs(text, keep_blank_values=True)
        return {k: v[0] if len(v) == 1 else v for k, v in parsed.items()}
    return {"raw_text": text}


def first_str(obj: Any, keys: tuple[str, ...]) -> str:
    if isinstance(obj, dict):
        for key in keys:
            val = obj.get(key)
            if isinstance(val, str) and val.strip():
                return val
    return ""


def append_text(parts: list[str], value: Any) -> None:
    if value is None:
        return
    if isinstance(value, str):
        s = value.strip()
        if s:
            parts.append(s)
        return
    if isinstance(value, (list, tuple)):
        for item in value:
            append_text(parts, item)
        return
    if isinstance(value, dict):
        for key in (
            "title", "text", "body", "message", "content", "big_text", "bigText",
            "sub_text", "subText", "summary_text", "summaryText", "text_lines", "textLines", "lines",
        ):
            if key in value:
                append_text(parts, value.get(key))


def combined_content(payload: Any) -> str:
    parts: list[str] = []
    append_text(parts, payload)
    seen: set[str] = set()
    out: list[str] = []
    for part in parts:
        if part not in seen:
            seen.add(part)
            out.append(part)
    content = "\n".join(out).strip()
    if len(content) > _ARGS.max_content_chars:
        content = content[: _ARGS.max_content_chars] + "\n..."
    return content


def check_key(handler: BaseHTTPRequestHandler) -> bool:
    got = handler.headers.get("X-Relay-Key", "").strip()
    if not got:
        got = handler.headers.get("X-Relay-Token", "").strip()  # backward-compatible header name
    auth = handler.headers.get("Authorization", "").strip()
    if auth.lower().startswith("bearer "):
        auth = auth[7:].strip()
    return bool(_RELAY_KEY) and (secrets.compare_digest(got, _RELAY_KEY) or secrets.compare_digest(auth, _RELAY_KEY))


def append_record(record: dict[str, Any]) -> int:
    global _LATEST, _COUNT
    output = Path(_ARGS.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    line = json.dumps(record, ensure_ascii=False, separators=(",", ":")) + "\n"
    with _WRITE_LOCK:
        with output.open("a", encoding="utf-8") as f:
            f.write(line)
            f.flush()
            if _ARGS.fsync:
                os.fsync(f.fileno())
        _LATEST = record
        _COUNT += 1
        return _COUNT


class NotifyReceiver(BaseHTTPRequestHandler):
    server_version = "NotifyReceiver/1.1"

    def do_GET(self) -> None:  # noqa: N802
        parsed = urllib.parse.urlparse(self.path)
        if parsed.path in ("/health", "/"):
            json_response(self, 200, {
                "ok": True,
                "service": "notify_receiver",
                "auth_required": True,
                "key_file": str(Path(_ARGS.key_file)),
                "records_in_process": _COUNT,
                "output": str(Path(_ARGS.output)),
            })
            return
        if parsed.path == "/latest":
            if not check_key(self):
                json_response(self, 401, {"ok": False, "error": "unauthorized"})
                return
            json_response(self, 200, {"ok": True, "latest": _LATEST})
            return
        json_response(self, 404, {"ok": False, "error": "not_found"})

    def do_POST(self) -> None:  # noqa: N802
        parsed = urllib.parse.urlparse(self.path)
        if parsed.path not in ("/", "/ingest", "/notify", "/webhook"):
            json_response(self, 404, {"ok": False, "error": "not_found"})
            return
        if not check_key(self):
            json_response(self, 401, {"ok": False, "error": "unauthorized"})
            return
        try:
            raw = read_body(self)
            payload = parse_payload(raw, self.headers.get("Content-Type", ""))
        except Exception as exc:
            json_response(self, 400, {"ok": False, "error": str(exc)})
            return

        qs = urllib.parse.parse_qs(parsed.query, keep_blank_values=True)
        ts, iso = utc_now()
        remark = ""
        if "remark" in qs and qs["remark"]:
            remark = qs["remark"][0]
        if not remark:
            remark = first_str(payload, ("remark", "note", "memo", "comment"))

        record = {
            "received_at": iso,
            "received_ts": ts,
            "path": parsed.path,
            "remark": remark,
            "client": {
                "ip": self.client_address[0] if self.client_address else "",
                "user_agent": self.headers.get("User-Agent", ""),
            },
            "content_type": self.headers.get("Content-Type", ""),
            "source": first_str(payload, ("source", "app", "from", "package")),
            "content": combined_content(payload),
            "payload": payload,
        }
        count = append_record(record)
        json_response(self, 200, {"ok": True, "stored": 1, "count_in_process": count, "received_at": iso})

    def log_message(self, fmt: str, *args: Any) -> None:
        if _ARGS.quiet:
            return
        ts = _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        print(f"[{ts}] {self.address_string()} {fmt % args}", flush=True)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generic authenticated POST receiver that appends received content to JSONL.")
    p.add_argument("--host", default="0.0.0.0")
    p.add_argument("--port", type=int, default=8788)
    p.add_argument("--output", default="data/notifications.jsonl")
    p.add_argument("--key-file", default="key.env", help="env file containing NOTIFY_RELAY_KEY; auto-created if missing")
    p.add_argument("--max-body-bytes", type=int, default=1024 * 1024)
    p.add_argument("--max-content-chars", type=int, default=20000)
    p.add_argument("--fsync", action="store_true", help="fsync after every write")
    p.add_argument("--quiet", action="store_true")
    return p.parse_args()


def main() -> None:
    global _ARGS, _RELAY_KEY
    _ARGS = parse_args()
    Path(_ARGS.output).parent.mkdir(parents=True, exist_ok=True)
    key_path = Path(_ARGS.key_file)
    _RELAY_KEY = load_or_create_key(key_path)
    srv = ThreadingHTTPServer((_ARGS.host, _ARGS.port), NotifyReceiver)
    print(f"Notify receiver listening on http://{_ARGS.host}:{_ARGS.port}", flush=True)
    print(f"Writing JSONL records to {Path(_ARGS.output).resolve()}", flush=True)
    print(f"Authentication key file: {key_path.resolve()} (value not printed)", flush=True)
    srv.serve_forever()


if __name__ == "__main__":
    main()
